function mesh=readinp(filename)
% This file is used to read the inp file generated by Abaqus
% This code can be further modified to improve the efficiency

fid = fopen(filename, 'r'); 
linum=0;
while ~feof(fid)
    linum=linum+1;
    tline = fgetl(fid);
    if strcmp(tline,'*Node')
        nodenum=linum;
    end
    if strncmp(tline,'*Element',8)
        elenum=linum;
    end
    if strncmp(tline,'*Nset',5) 
        setnum=linum;
    end
end
fclose(fid);

fid = fopen(filename, 'r'); 
mesh.node=zeros(elenum-nodenum-1,2);
mesh.topo=zeros(setnum-elenum-1,4);
linum=0;
node_index=0;
topo_index=0;
while ~feof(fid)
    linum=linum+1;
    tline = fgetl(fid);
    if  linum>nodenum&& linum<elenum
        node_index=node_index+1;
        tline=str2num(tline);
        mesh.node(node_index,:)=tline(2:3);
    end
    if  linum>elenum&& linum<setnum
        topo_index=topo_index+1;
        tline=str2num(tline);
        mesh.topo(topo_index,:)=tline(2:5);
    end 
end
fclose(fid);

end
